name: carlosarriaga/react-native
author:
  name: Carlos Arriaga
  email: carlitos.arriaga@outlook.com
  url: null
copyright: 2015 Carlos Arriaga
description: A framework for building native apps with React.
